env_path: ".env"
model_path: "Qwen/Qwen3-0.6B-Base"
dataset_path: "Ritvik19/gsm8k-onpolicy-Qwen3-0.6B-cpt"
output_dir: "models/clm_qwen_gsm8k"

# WandB settings
wandb_project: "nanoformers"
wandb_run_name: "clm_qwen_gsm8k"

# Training settings
batch_size: 16
gradient_accumulation_steps: 1
num_epochs: 2
learning_rate: 5e-6
lr_scheduler_type: "cosine"
max_length: 1024
device: "cuda"
load_weights: true
bos_token_id: None
