env_path: ".env"
model_path: "bert-base-uncased"
dataset_path: "Ritvik19/open-web-text"
output_dir: "models/mlm_bert_open_web_text"

# WandB settings
wandb_project: "nanoformers"
wandb_run_name: "mlm_bert_open_web_text"

# Training settings
batch_size: 128
gradient_accumulation_steps: 1
num_epochs: 1
learning_rate: 5e-5
lr_scheduler_type: "cosine"
max_length: 512
mlm_probability: 0.15
device: "cuda"
load_weights: true
