env_path: ".env"
model_path: "distilbert/distilbert-base-uncased"
dataset_path: "Ritvik19/dair-ai-emotion"
output_dir: "models/seqclf_distilbert_dair-ai-emotion"

# WandB settings
wandb_project: "nanoformers"
wandb_run_name: "seqclf_distilbert_dair-ai-emotion"

# Training settings
batch_size: 128
gradient_accumulation_steps: 1
num_epochs: 3
learning_rate: 2e-5
lr_scheduler_type: "cosine"
max_length: 512
device: "cuda"
