env_path: ".env"
model_path: "google/flan-t5-base"
dataset_path: "Ritvik19/gsm8k-seq2seq"
output_dir: "models/seq2seq_flan_t5_base_gsm8k_lora"

# WandB settings
wandb_project: "nanoformers"
wandb_run_name: "seq2seq_flan_t5_base_gsm8k_lora"

# Training settings
batch_size: 16
gradient_accumulation_steps: 1
num_epochs: 250
learning_rate: 5e-5
lr_scheduler_type: "cosine"
max_length: 1024
device: "cuda"

# LoRA / QLoRA settings
peft:
  use_lora: true
  use_qlora: false
  r: 128
  alpha: 256
  dropout: 0.05
  target_modules: null      # auto-inferred for T5: [q, k, v, o]
  modules_to_save: null
  save_mode: "adapter"
